openapi: 3.0.0

info:
  title: Dummy application
  description: Dummy application to test different devops tools
  version: 1.0.0


paths:
  /:
    get:
      summary: "Get homepage"
      operationId: "homepage"
      responses:
        '200':
          description: "A JSON"
          content:
            text/plain:
              schema:
                type: string


