# coding: utf-8

# flake8: noqa
"""
    Dummy application

    Dummy application to test different devops tools  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
